name = "Modified Cobblemon Overclocked"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac433912c2862ffb7400ba6eb884ec24ccffab8eb17b8ea9e43e7a1a513d2f7c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
