name = "Modified Cobblemon Overclocked"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f833abb5e3e393e2acbcdd43fa9120a997535b02f5f04a58bbb9e7579dcb737f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
