name = "Modified Cobblemon Overclocked"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afeb452330b203e837b04dcfc6e9fcb1d39e12ab74d4444eb99600a7763553d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
