name = "Modified Cobblemon Overclocked"
version = "1.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca035839c12df5309737cc3461676ef14dca1c4c25c075cc9fa30ca6c80e4a8c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.208"

[export]
[export.curseforge]
acceptable-game-versions = ["1.21.1"]
project-id = 1206395
