name = "Modified Cobblemon Overclocked"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86ab8307fdd31dbfcee65015405c1a883ca5165f8f56caf8ea75e916462b76dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
