name = "Modified Cobblemon Overclocked"
version = "1.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b337b72d4143182e33e54c005b48d069be14038c41bf0b90149cb92ba83d6fed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
