name = "Modified Cobblemon Overclocked"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28449d5416b5fa7cc08bc67f463d65de72b274b7ca87d4e24e5f8156c36550d4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
