name = "Modified Cobblemon Overclocked"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d057f53783652b10804afba1249516fef35c6198b1acc78067733c83a38c089"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
