name = "Modified Cobblemon Overclocked"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37cf0721b627955b1ce10e110c40ee7a67f9e3683bcf1cd29b5ee7f7397d7ead"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
