name = "Modified Cobblemon Overclocked"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80b159cfb5ef0c6263622b57432b6b978ff89556845f4172b8aec49811363597"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
