name = "Modified Cobblemon Overclocked"
version = "1.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78e1469bd716fcababd2e39ea6891401a8b237cb861232c07719d19c75268688"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
