name = "Modified Cobblemon Overclocked"
version = "1.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09f7815c95c615f69d6dc23921b8b0f4eb9f7deb34c6b84aa24498cf918a43e7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
