name = "Modified Cobblemon Overclocked"
version = "1.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57f2efc25385f5a5ccf96ec9519e507b5920d1170e526292748dba2466278de1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
