name = "Modified Cobblemon Overclocked"
version = "1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69bdfafb9f82cca6eb3eab92d1c6b63c29684d612b31c76443d3b6245653c8dc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
