name = "Modified Cobblemon Overclocked"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9bf23ff3bb22c4d518cd377f5c4c4a91ffdcb58b5c99323bee37fbe21e9fa51"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.171"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
