name = "Modified Cobblemon Overclocked"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "349ba20b4ce455e09bd326ce499c37c0f2b08090542dbe57670e1e6b69bfa5bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
