name = "Modified Cobblemon Overclocked"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adacf3f02d327409404d3e3a60d6f01af1468f39c3212d5eb5652a53806ec5cc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
