name = "Modified Cobblemon Overclocked"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c748e305651a9c99a39b6f85d1c1a0e161a661f074b25f1f530a560fba7e215"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
