name = "Modified Cobblemon Overclocked"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "008696d701fafa73c7d4b0a31099091b3bc2079c3db1fefa5d6cad47c7f2601e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.171"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
